name: NeoEmu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MinGW (GCC)
      uses: swyx/github-actions-setup-minGW@v1

    - name: Compile C++ code
      run: |
        g++ -o output.exe main.cpp

    - name: Upload .exe artifact
      uses: actions/upload-artifact@v2
      with:
        name: executable
        path: output.exe
